config/routes.rb
Nerdwallet::Application.routes.draw do
  resources :securities, :only => [:index]

  match '/' => 'securities#index'
  match 'getPrice/:id' => 'securities#getPrice'

end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :cummulativeCashDividend, :cummulativeStockDividendRatio, :date, :delay, :high, :lastClose, :low, :open, 
  				  :volume,:security_id,:last, :changeFromLastClose
  belongs_to :security
end

app/models/security.rb
class Security < ActiveRecord::Base
  attr_accessible :name, :symbol
  has_many :prices
  validates_uniqueness_of :symbol
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
  # GET /securities
  # GET /securities.json
  def index
    @securities = Security.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @securities }
    end
  end

  # GET /securities/1
  # GET /securities/1.json
  def show
    @security = Security.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @security }
    end
  end


  # GET /getPrice/1.json
  def getPrice
    security_id = params[:id]
    @prices = Price.find_all_by_security_id(security_id)

    respond_to do |format|
      format.json {render json: @prices}
    end
  end

  # GET /securities/new
  # GET /securities/new.json
  def new
    @security = Security.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @security }
    end
  end

  # GET /securities/1/edit
  def edit
    @security = Security.find(params[:id])
  end

  # POST /securities
  # POST /securities.json
  def create
    @security = Security.new(params[:security])

    respond_to do |format|
      if @security.save
        format.html { redirect_to @security, notice: 'Security was successfully created.' }
        format.json { render json: @security, status: :created, location: @security }
      else
        format.html { render action: "new" }
        format.json { render json: @security.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /securities/1
  # PUT /securities/1.json
  def update
    @security = Security.find(params[:id])

    respond_to do |format|
      if @security.update_attributes(params[:security])
        format.html { redirect_to @security, notice: 'Security was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @security.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /securities/1
  # DELETE /securities/1.json
  def destroy
    @security = Security.find(params[:id])
    @security.destroy

    respond_to do |format|
      format.html { redirect_to securities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nerdwallet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>


  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/securities/_form.html.erb
<%= form_for(@security) do |f| %>
  <% if @security.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@security.errors.count, "error") %> prohibited this security from being saved:</h2>

      <ul>
      <% @security.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/securities/edit.html.erb
<h1>Editing security</h1>

<%= render 'form' %>

<%= link_to 'Show', @security %> |
<%= link_to 'Back', securities_path %>

app/views/securities/index.html.erb
<div class="input-container">
  <button id="button">Clear Chart</button>
  <input id="searchInput" class="" type="text" placeholder="Start Typing Stock Symbal">
</div>

<div class="chart-container" id="chart"></div>

app/views/securities/new.html.erb
<h1>New security</h1>

<%= render 'form' %>

<%= link_to 'Back', securities_path %>

app/views/securities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @security.name %>
</p>

<p>
  <b>Symbol:</b>
  <%= @security.symbol %>
</p>


<%= link_to 'Edit', edit_security_path(@security) %> |
<%= link_to 'Back', securities_path %>